### ISSUE TITLE
Getting videos of channel not working

### ISSUE THREAD

**Issue by derSeddy** [dermasmid/scrapetube#11]
It seems that getting videos for a channel is not working because the html youtube responds doesn't contain the desired json anymore.

Consider the example
```python
import scrapetube

videos = scrapetube.get_channel("UCCezIgC97PvUuR4_gbFUs5g")

for video in videos:
    print(video['videoId'])
```
it currently only leads to
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[removed for privacy]/.local/lib/python3.8/site-packages/scrapetube/scrapetube.py", line 46, in get_channel
    for video in videos:
  File "[removed for privacy]/.local/lib/python3.8/site-packages/scrapetube/scrapetube.py", line 142, in get_videos
    client = json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I'm using the latest version 2.2.2. The search example still works fine.

**Comment by titaii2** [comment]
Hello,
Same for me. It was working few days ago, but since yesterday, it doesn't work anymore with the same error.

**Comment by sylvqin** [comment]
It seems there was a glitch regarding the Youtube Consent page.
Fixed it by removing a condition line that wasn't met anymore - probably due to a Youtube update. Seems to be working just as before :)

(Thanks btw for that wonderful tool!)

**Comment by titaii2** [comment]
We just need @dermasmid to accept the pull request now ;)

**Comment by dermasmid** [comment]
I cannot reproduce the error, but will approve the pr if that fixes it for you guys

**Comment by derSeddy** [comment]
I can confirm, that the fix works for me.

**Comment by rootinthemood** [comment]
Have the same issue.
Can also confirm sylvqin's fix is working.

**Comment by dermasmid** [comment]
fixed in version 2.3.0

**Comment by Sanyamkhankhoje** [comment]
It seems that this issue still permits, I am using 2.3.1 version of scrapetube and still facing this issue while scraping with channel_ids. Can anyone please help with this?

**Comment by criscons** [comment]
Hello,
I have the same issue, I'm using the latest version 2.5.0 It was working few days ago, but it doesn't work anymore with the same error.
